name: Avro Compatibility Tests
on: [push, pull_request]
jobs:
  test:
    name: "Compatibility: avro ${{ matrix.avro }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0", "1.11.1"]
        gradle: ["5.1", "7.6"]
        java: ["8"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
      - uses: gradle/actions/setup-gradle@v3
        with:
          build-root-directory: lang/java/gradle-plugin
          gradle-version: wrapper
          arguments: testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
