name: OS Compatibility
on: [push, pull_request]
jobs:
  build:
    name: "Compatibility: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [11]
        os: [ubuntu-latest, windows-latest, macOS-latest] # All supported OS
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
      - uses: gradle/actions/setup-gradle@v3
        with:
          build-root-directory: lang/java/gradle-plugin
          gradle-version: wrapper
          arguments: test
